- hosts: all
  become: true
  tasks:
    - name: Instalar dependências básicas
      yum:
        name:
          - curl
          - yum-utils
          - git
        state: present
        update_cache: yes

    - name: Instalar Docker
      yum:
        name: docker
        state: present

    - name: Garantir que o Docker está ativo
      service:
        name: docker
        state: started
        enabled: yes

    - name: Instalar K3s
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        executable: /bin/bash

    - name: Parar container existente (se houver)
      shell: |
        docker stop analyzer-api || true
        docker rm analyzer-api || true
      args:
        executable: /bin/bash

    - name: Pull e executar container Go
      shell: |
        docker pull ${{ secrets.DOCKER_REGISTRY }}/analyzer-api:latest
        docker run -d -p 8080:8080 --name analyzer-api ${{ secrets.DOCKER_REGISTRY }}/analyzer-api:latest
      args:
        executable: /bin/bash

    - name: Health check da aplicação
      shell: |
        for i in {1..5}; do
          curl -f http://localhost:8080/health && exit 0 || sleep 5
        done
        exit 1
      args:
        executable: /bin/bash
